version: '3'
services:
  db:
    image: mysql:8.1.0
    environment:
      TZ: Europe/Budapest
      MYSQL_ROOT_PASSWORD: supersecret
    volumes:
      - ./db/sql:/docker-entrypoint-initdb.d # Run every sql script what's in this directory
      - ./db/data:/var/lib/mysql/ # Mount data to the host to don't lose DB at restart
    ports:
      - "3306:2206"
    networks:
      - bridge

  smart-home:
    build: ./backend/
    depends_on:
      - db
    restart: unless-stopped
    environment:
      DB_USER: root
      DB_PASS: supersecret
      DB_PORT: 3306
      DB_HOST: db
    ports:
      - "8088:8088"
    networks:
      - bridge

networks:
  bridge: