version: '3'
services:
  mysql:
    image: mysql:8.1.0
    environment:
      MYSQL_ROOT_PASSWORD: supersecret
      #MYSQL_DATABASE: smarthome
    volumes:
      # Run every sql script what's in this directory
      - ./sql-scripts:/docker-entrypoint-initdb.d

  smart-hom:
    build: .
    depends_on:
      - mysql
    restart: unless-stopped
    environment:
      - ROOT_PASSWORD=supersecret
      - MYSQL_USER=root
      - MYSQL_PASSWORD=supersecret
      - MYSQL_DATABASE=smarthome
    ports:
      - "8088:8088"
